# Errors & Exception
## 에러와 예외
### 디버깅
#### 버그 `bug`
소프트웨어에서 발생하는 오류 또는 결함<br>
프로그램의 예상된 동작과 실제 동작 사이의 불일치
#### 버그의 기원
- 최초의 버그는 1945년 프로그래밍 언어의 일종인 코볼 발명자 그레이스 호퍼가 발견
- 역사상 최초의 컴퓨터 버그는 Mark Ⅱ라는 컴퓨터 회로에 벌레인 나방이 들어가 <br>합선을 일으켜 비정상적으로 동작한 것을 기록한 것
- "버그"라는 용어는 이전부터 사용되어 왔지만 이 사건을 계기로 컴퓨터 시스템에서 <br>발생하는 오류 또는 결함을 지칭하는 용어로 널리 사용되기 시작
#### Debugging
소프트웨어에서 발생하는 버그를 찾아내고 수정하는 과정<br>
프로그램의 오작동 원인을 식별하여 수정하는 작업
#### 디버깅 방법
1. print 함수 활용
    - 특정 함수 결과, 반복/조건 결과 등 나눠서 생각, 코드를 bisection으로 나눠서 생각
2. 개발 환경(text editor, IDE) 등에서 제공하는 기능 활용
    - breakpoint, 변수 조회 등
3. [Python tutor](https://pythontutor.com/) 활용 (단순 파이썬 코드인 경우) 
4. 뇌 컴파일, 눈 디버깅 등
### 에러
#### 에러 `Error`
프로그램 실행 중에 발생하는 예외 상황
#### 파이썬의 에러 유형
- 문법 에러 `Syntax Error`
    - 프로그램의 구문이 올바르지 않은 경우 발생 <br>(오타, 괄호 및 콜론 누락 등의 문법적 오류)
- 예외 `Exception`
    - 프로그램 실행 중에 감지되는 에러
#### 문법 에러 예시
- Invalid syntax (문법 오류)
    
    ```py
    while # SyntaxError: invalid syntax
    ```

- assign to literal (잘못된 할당)
    
    ```py
    5=3 # SyntaxError: cannot assign to literal
    ```

- EOL (End of Line)
    
    ```py
    print('hello   
    # SyntaxError: EOL while scanning string literal
    ```

- EOF (End of File)
    
    ```py
    print(
    #SyntaxError: unexpected EOF while parsing
    ```

### 예외
#### 예외 `Exception`
프로그램 실행 중에 감지되는 에러
#### 내장 예외 `Built-in Exceptions`
- 예외 상황을 나타내는 예외 클래스들
- 파이썬에서 이미 정의되어 있으며, <br>특정 예외 상황에 대한 처리를 위해 사용
> 참고 문서 : https://docs.python.org/ko/3/library/exceptions.html#ValueError

#### 예외 예시
- ZeroDivisionError : 나누기 또는 모듈로 연산의 두 번째 인자가 0일 때 발생
    
    ```py
    10/0 # ZeroDivisionError: division by zero
    ```
    
- NameError : 지역 또는 전역 이름을 찾을 수 없을 때 발생
    
    ```py
    print(name_error) # NameError: name 'name_error' is not defined
    ```

- TypeError 
    - 타입 불일치
        
        ```py
        '2' + 2  # TypeError: can only concatenate str (not "int") to str
        ```

    - 인자 누락
        
        ```py
        sum()  # TypeError: sum() takes at least 1 positional argument (0 given)
        ```
    
    - 인자 초과

        ```py
        sum(1, 2, 3)  # TypeError: sum() takes at most 2 arguments (3 given)
        ```

    - 인자 타입 불일치
        
        ```py
        import random
        random.sample(1, 2)
        # TypeError: Population must be a sequence.  For dicts or sets, use sorted(d).
        ```

- ValueError 
    - 연산이나 함수에 문제가 없지만 부적절한 값을 가진 인자를 받았고, <br>상황이 IndexError 처럼 더 구체적인 예외로 설명되지 않는 경우 발생

    ```py
    int('1.5') # ValueError: invalid literal for int() with base 10: '3.5'

    range(3).index(6) # ValueError: 6 is not in range
    ```

- IndexError – 시퀀스 인덱스가 범위를 벗어날 때 발생
    
    ```py
    empty_list = []
    empty_list[2]
    # IndexError: list index out of range
    ```
    
- KeyError – 딕셔너리에 해당 키가 존재하지 않는 경우
    
    ```py
    person = {'name': 'Alice'}
    person['age']  # KeyError: 'age'
    ```

- ModuleNotFoundError - 모듈을 찾을 수 없을 때 발생
    
    ```py
    import hahaha  # ModuleNotFoundError: No module named 'hahaha'
    ```

- ImportError – 임포트 하려는 이름을 찾을 수 없을 때 발생
    
    ```py
    from random import hahaha
    # ImportError: cannot import name 'hahaha' from 'random'
    ```

- KeyboardInterrupt – 사용자가 Control-C 또는 Delete를 누를 때 발생
    - 무한루프 시 강제 종료
    
    ```py
    while True: 
        continue
    
    '''
    Traceback (most recent call last):
      File "...", line 2, in <module>
        continue
    KeyboardInterrupt
    '''
    ```

- IndentationError - 잘못된 들여쓰기와 관련된 문법 오류
    
    ```py
    for i in range(10):
    print(i) # IndentationError: expected an indented block
    ```

### 예외 처리
#### try 와 except
파이썬에서는 <span style='color:red;'>try</span> 문과 <span style='color:red;'>except</span> 절을 사용하여 예외 처리

#### try-except 구조
- try 블록 안에는 예외가 발생할 수 있는 코드를 작성
- except 블록 안에는 예외가 발생했을 때 처리할 코드를 작성
- 예외가 발생하면 프로그램 흐름은 try 블록을 빠져나와 해당 예외에 <br>대응하는 except 블록으로 이동

    ```py
    try:
        # 예외가 발생할 수 있는 코드

    except 예외:
        # 예외 처리 코드
    ```
#### 예외 처리 예시 1

```py
try:
    result = 10 / 0
except ZeroDivisionError:
    print('0으로 나눌 수 없습니다.')
# 0으로 나눌 수 없습니다.
```

#### 예외 처리 예시 2
```py
try:
    num = int(input('숫자입력 : '))
except ValueError:
    print('숫자가 아닙니다.')

"""
숫자입력 : a
숫자가 아닙니다.
"""
```
#### 복수 예외 처리 연습 (1/4)
- 100을 사용자가 입력한 값으로 나누고 출력하는 코드를 작성해보시오.
    - 먼저, 발생 가능한 에러가 무엇인지 예상해보기

        ```py
        num = int(input('100으로 나눌 값을 입력하시오 : '))
        print(100 / num)
        ```
#### 복수 예외 처리 연습 (2/4)
- 100을 사용자가 입력한 값으로 나누고 출력하는 코드를 작성해보시오.
    - 먼저, 발생 가능한 에러가 무엇인지 예상해보기

        ```py
        num = int(input('100으로 나눌 값을 입력하시오 : '))
        print(100 / num)

        # int(’a’)
        # 100/int(’0’)
        ```
#### 복수 예외 처리 연습 (3/4)
- 100을 사용자가 입력한 값으로 나누고 출력하는 코드를 작성해보시오.
    - 먼저, 발생 가능한 에러가 무엇인지 예상해보기

        ```py
        num = int(input('100으로 나눌 값을 입력하시오 : '))
        print(100 / num)

        """
        int(’a’)
        문자열을 int로 형변환 : ValueError
        """

        """
        100 / 0
        0으로 숫자를 나눔 : ZeroDivisionError
        """
        ```
#### 복수 예외 처리 연습 (4/4)
- 100을 사용자가 입력한 값으로 나누고 출력하는 코드를 작성해보시오.
    - 발생가능한 에러를 모두 명시하거나 & 별도로 작성하기
    - 모두 명시
        
        ```py
        try:
            num = int(input('100으로 나눌 값을 입력하시오 : '))
            print(100 / num)
        except (ValueError, ZeroDivisionError):
            print('제대로 입력해주세요.')
        ```

    - 별도 작성
        
        ```py
        try:
            num = int(input('100으로 나눌 값을 입력하시오 : '))
            print(100 / num)
        except ValueError:
            print('숫자를 넣어주세요.')
        except ZeroDivisionError:
            print('0으로 나눌 수 없습니다.')
        except:
            print('에러가 발생하였습니다.')
        ```
      - 입력한 에러 이외의 에러가 발생했을 때 
#### 내장 예외의 상속 계층구조 주의 (1/2)
- 아래와 같이 예외를 작성하면 코드는 2번째 except 절에 이후로 도달하지 못함 
    
    ```py
    try:
        num = int(input('100으로 나눌 값을 입력하시오 : '))
        print(100 / num)
    except BaseException:
        print('숫자를 넣어주세요.')
    # 아래 블록은 도달하지 못함.
    except ZeroDivisionError:
        print('0으로 나눌 수 없습니다.')
    except:
        print('에러가 발생하였습니다.')
    ```
#### 내장 예외의 상속 계층구조 주의 (2/2)
- 내장 예외 클래스는 상속 계층구조를 가지기 때문에 <br>except 절로 분기 시 **  반드시 하위 클래스를 먼저 확인 할 수 있도록 ** 작성해야 함

    ```py
    try:
        num = int(input('100으로 나눌 값을 입력하시오 : '))
        print(100 / num)
    except BaseException: # 하위 예외 클래스 확인 필요
        print('숫자를 넣어주세요.')
    except ZeroDivisionError: # 하위 예외 클래스 확인 필요
        print('0으로 나눌 수 없습니다.')
    except:
        print('에러가 발생하였습니다.')
    ```
    
    ![image](https://github.com/ragu6963/TIL/assets/32388270/6ce033c9-6715-473f-a6c2-9e2288361a1a)

> 참고 문서 : https://docs.python.org/ko/3/library/exceptions.html#exception-hierarchy

## 참고
### as 키워드
#### as 키워드
- as 키워드를 활용하여 에러 메시지를 except 블록에서 사용할 수 있음
- 해당하는 except 구문 안에서만 사용할 수 있음.

    ```py
    my_list = []

    try:
        number = my_list[1]
    except IndexError as error:
        print(f'{error}가 발생했습니다.')

    # list index out of range가 발생했습니다.
    ```
